symlink

diff --git a/build/nix/etc/nix_direnvrc b/build/nix/etc/nix_direnvrc
--- a/build/nix/etc/nix_direnvrc
+++ b/build/nix/etc/nix_direnvrc
@@ -48,7 +48,7 @@ _nix_direnv_preflight () {
 nix_direnv_version() {
   declare major='2' minor='2' patch='0' # UPDATE(nix-direnv version)
 
-  [[ $1 =~ ^([^+-.]*)(\.?)([^+-.]*)(\.?)([^+-]*)(-?)([^+]*)(\+?)(.*)$ ]]
+  [[ ${1} =~ ^([^+-.]*)(\.?)([^+-.]*)(\.?)([^+-]*)(-?)([^+]*)(\+?)(.*)$ ]]
   declare -a ver; ver=("${BASH_REMATCH[@]:1}")
 
   req_major=${ver[0]}
@@ -62,7 +62,7 @@ nix_direnv_version() {
     || ( ${ver[7]} == '+' && ${ver[8]} != +([0-9A-Za-z-])*(.+([0-9A-Za-z-])) ) \
     || ( ( -n ${ver[5]} || -n ${ver[7]} ) && ( -z ${ver[2]} || -z ${ver[4]} ) ) \
   ]]; then
-    printf '%s\n' "nix-direnv: error v$1 is not a valid semver version" >&2
+    printf '%s\n' "nix-direnv: error v${1} is not a valid semver version" >&2
     return 1
   fi
 
@@ -70,21 +70,21 @@ nix_direnv_version() {
      || ($req_major -eq $major && $req_minor -gt $minor) \
      || ($req_major -eq $major && $req_minor -eq $minor && $req_patch -gt $patch)
   ]]; then
-    printf '%s\n' "nix-direnv: error current version v$major.$minor.$patch is older than the desired version v$1" >&2
+    printf '%s\n' "nix-direnv: error current version v$major.$minor.$patch is older than the desired version v${1}" >&2
     return 1
   fi
 }
 
 _nix_direnv_realpath () {
     if has realpath; then
-      realpath "$1"
+      realpath "${1}"
     else
-      perl -e 'use Cwd "abs_path";print abs_path(shift)' "$1"
+      perl -e 'use Cwd "abs_path";print abs_path(shift)' "${1}"
     fi
 }
 
 _nix_export_or_unset() {
-  local key=$1 value=$2
+  local key=${1} value=${2}
   if [[ "$value" == __UNSET__ ]]; then
     unset "$key"
   else
@@ -93,7 +93,7 @@ _nix_export_or_unset() {
 }
 
 _nix_import_env() {
-  local profile_rc=$1
+  local profile_rc=${1}
 
   local old_nix_build_top=${NIX_BUILD_TOP:-__UNSET__}
   local old_tmp=${TMP:-__UNSET__}
@@ -128,8 +128,8 @@ _nix_strip_escape_path() {
 }
 
 _nix_add_gcroot() {
-  local storepath=$1
-  local symlink=$2
+  local storepath=${1}
+  local symlink=${2}
   local escaped_symlink
   escaped_symlink=$(_nix_strip_escape_path "$symlink")
 
@@ -138,7 +138,7 @@ _nix_add_gcroot() {
 }
 
 _nix_clean_old_gcroots() {
-  local layout_dir=$1
+  local layout_dir=${1}
   local escaped_layout_dir
   escaped_layout_dir=$(_nix_strip_escape_path "$layout_dir")
 
@@ -150,12 +150,12 @@ _nix_clean_old_gcroots() {
 
 _nix_argsum_suffix() {
   local out checksum
-  if [ -n "$1" ]; then
+  if [ -n "${1}" ]; then
 
     if has sha1sum; then
-      out=$(sha1sum <<< "$1")
+      out=$(sha1sum <<< "${1}")
     elif has shasum; then
-      out=$(shasum <<< "$1")
+      out=$(shasum <<< "${1}")
     else
       # degrate gracefully both tools are not present
       return
@@ -166,8 +166,8 @@ _nix_argsum_suffix() {
 }
 
 nix_direnv_watch_file() {
-  watch_file "$@"
-  nix_watches+=("$@")
+  watch_file "${@}"
+  nix_watches+=("${@}")
 }
 
 use_flake() {
@@ -212,7 +212,7 @@ use_flake() {
     local tmp_profile_rc
     tmp_profile_rc=$("${NIX_BIN_PREFIX}nix" print-dev-env \
       --extra-experimental-features "nix-command flakes" \
-      --profile "$tmp_profile" "$@")
+      --profile "$tmp_profile" "${@}")
 
     local drv
     drv=$(_nix_direnv_realpath "$tmp_profile")
@@ -270,7 +270,7 @@ use_nix() {
   fi
 
   local profile
-  profile="${layout_dir}/nix-profile-${version:-unknown}$(_nix_argsum_suffix "$*")"
+  profile="${layout_dir}/nix-profile-${version:-unknown}$(_nix_argsum_suffix "${*}")"
   local profile_rc="${profile}.rc"
 
   local in_packages=0
@@ -285,8 +285,8 @@ use_nix() {
     nixfile="./default.nix"
   fi
 
-  while [[ "$#" -gt 0 ]]; do
-    i="$1"
+  while [[ "${#}" -gt 0 ]]; do
+    i="${1}"
     shift
 
     case $i in
@@ -303,15 +303,15 @@ use_nix() {
         # ignore them
         ;;
       --include|-I)
-        extra_args+=("$i" "$1")
+        extra_args+=("$i" "${1}")
         shift
         ;;
       --attr|-A)
-        attribute="$1"
+        attribute="${1}"
         shift
         ;;
       --option|-o|--arg|--argstr)
-        extra_args+=("$i" "$1" "$2")
+        extra_args+=("$i" "${1}" "${2}")
         shift
         shift
         ;;
@@ -384,7 +384,7 @@ use_nix() {
   _nix_import_env "$profile_rc"
 
 
-  if [[ "$#" == 0 ]]; then
+  if [[ "${#}" == 0 ]]; then
     watch_file default.nix
     watch_file shell.nix
   fi
